In [28]:
import numpy as np
import pandas as pd
import matplotlib.pyplot 

In [29]:
df = pd.read_csv("Churn_Modelling.csv")

In [30]:
df.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
RowNumber          10000 non-null int64
CustomerId         10000 non-null int64
Surname            10000 non-null object
CreditScore        10000 non-null int64
Geography          10000 non-null object
Gender             10000 non-null object
Age                10000 non-null int64
Tenure             10000 non-null int64
Balance            10000 non-null float64
NumOfProducts      10000 non-null int64
HasCrCard          10000 non-null int64
IsActiveMember     10000 non-null int64
EstimatedSalary    10000 non-null float64
Exited             10000 non-null int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB


In [32]:
X=df.iloc[:,3:-1].values

In [33]:
y=df.iloc[:,-1].values

**Handling Categorical values**

In [34]:
X[0][0]

619

In [8]:
X

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [9]:
from sklearn.preprocessing import LabelEncoder ,OneHotEncoder

leX1= LabelEncoder()
X[:,1]=leX1.fit_transform(X[:,1])

leX2= LabelEncoder()
X[:,2]=leX2.fit_transform(X[:,2])

In [10]:
leX1.classes_

array(['France', 'Germany', 'Spain'], dtype=object)

In [11]:
oneHotEncoder= OneHotEncoder(categorical_features=[1])

In [12]:
X=oneHotEncoder.fit_transform(X).toarray()

C:\Users\KINJAL\.conda\envs\py3\lib\site-packages\sklearn\preprocessing\_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
C:\Users\KINJAL\.conda\envs\py3\lib\site-packages\sklearn\preprocessing\_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [13]:
X[:,0]

array([1., 0., 1., ..., 1., 0., 1.])

In [14]:
X[5][2]

1.0

In [15]:
X.info()

AttributeError: 'numpy.ndarray' object has no attribute 'info'

In [16]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=29)

In [17]:
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train= sc.fit_transform(X_train)
X_test=sc.fit_transform(X_test)

In [18]:
X_train

array([[-0.99675526, -0.57965968,  1.73147365, ...,  0.6493972 ,
         0.96269532,  0.66627932],
       [ 1.0032553 , -0.57965968, -0.57754272, ...,  0.6493972 ,
        -1.03875025,  0.29417091],
       [-0.99675526, -0.57965968,  1.73147365, ...,  0.6493972 ,
         0.96269532, -0.41928646],
       ...,
       [-0.99675526,  1.72515018, -0.57754272, ...,  0.6493972 ,
         0.96269532,  0.63344535],
       [-0.99675526,  1.72515018, -0.57754272, ...,  0.6493972 ,
        -1.03875025,  0.90558036],
       [-0.99675526,  1.72515018, -0.57754272, ...,  0.6493972 ,
        -1.03875025,  1.53890225]])

In [1]:
import keras
from keras.models import Sequential
from keras.layers import Dense

ModuleNotFoundError: No module named 'keras'

In [3]:
classifier = Sequential()

NameError: name 'Sequential' is not defined

In [22]:
k=619

In [23]:
s=k.astype(float)

AttributeError: 'int' object has no attribute 'astype'

In [25]:
float(619)

619.0

In [27]:
X[0][0]

1.0

In [1]:
import keras

ModuleNotFoundError: No module named 'keras'